BEGIN ;

DROP TABLE IF EXISTS usres, posts, comments, votes CASCADE;

CREATE TABLE users (
id SERIAL PRIMARY KEY,
username VARCHAR(50) UNIQUE NOT NULL,
email VARCHAR(50) UNIQUE NOT NULL,
password VARCHAR NOT NULL
);

CREATE TABLE posts (
id SERIAL PRIMARY KEY ,
title VARCHAR(100) UNIQUE NOT NULL,
text TEXT NOT NULL,
date DATE NOT NULL,
date_edit DATE,
user_id INTEGER NOT NULL REFERENCES users(id) ON UPDATE CASCADE
);

CREATE TABLE comments (
id SERIAL PRIMARY KEY,
text TEXT NOT NULL,
user_id INTEGER NOT NULL REFERENCES users(id) ON UPDATE CASCADE ,
post_id INTEGER NOT NULL REFERENCES posts(id) ON UPDATE CASCADE,
comments_id INTEGER NOT NULL REFERENCES comments(id) ON UPDATE CASCADE
);

CREATE TABLE votes (
id SERIAL PRIMARY KEY,
stutas INTEGER NOT NULL,
user_id INTEGER NOT NULL REFERENCES users(id) ON UPDATE CASCADE ,
post_id INTEGER NOT NULL REFERENCES posts(id) ON UPDATE CASCADE,
comments_id INTEGER NOT NULL REFERENCES comments(id) ON UPDATE CASCADE
);

COMMIT ;